name: Deploy To Railway (STG)
on:
    push:
        branches:
            - 'stg'
            - 'debug-failing-ga-deployments'
jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Use Node 16
              uses: actions/setup-node@v3
              with:
                node-version: '16.x'

            - name: Install Railway
              run: npm i -g @railway/cli

            - name: Install Doppler CLI
              uses: dopplerhq/cli-action@v2
            - name: Run start.sh
              run: export DOPPLER_TOKEN="$(doppler configs tokens create --project author --config stg docker-stg-token --plain)"

            - name: Deploy To STG
              run: railway up
              env:
                RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
                DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN }}
